version: '3.8'

services:
  app:
    container_name: node-ts-book-management
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/book-management
    depends_on:
      - mongo
    restart: unless-stopped

  test:
    container_name: node-ts-book-test
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=test
      - MONGO_URL=mongodb://mongo:27017/book-api-test
    depends_on:
      - mongo
    command: npm run test
    
  mongo:
    container_name: mongo-db
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: